// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocktest

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockSomeDepInterface creates a new instance of MockSomeDepInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSomeDepInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSomeDepInterface {
	mock := &MockSomeDepInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSomeDepInterface is an autogenerated mock type for the SomeDepInterface type
type MockSomeDepInterface struct {
	mock.Mock
}

type MockSomeDepInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSomeDepInterface) EXPECT() *MockSomeDepInterface_Expecter {
	return &MockSomeDepInterface_Expecter{mock: &_m.Mock}
}

// SomeMethod provides a mock function for the type MockSomeDepInterface
func (_mock *MockSomeDepInterface) SomeMethod() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for SomeMethod")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockSomeDepInterface_SomeMethod_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SomeMethod'
type MockSomeDepInterface_SomeMethod_Call struct {
	*mock.Call
}

// SomeMethod is a helper method to define mock.On call
func (_e *MockSomeDepInterface_Expecter) SomeMethod() *MockSomeDepInterface_SomeMethod_Call {
	return &MockSomeDepInterface_SomeMethod_Call{Call: _e.mock.On("SomeMethod")}
}

func (_c *MockSomeDepInterface_SomeMethod_Call) Run(run func()) *MockSomeDepInterface_SomeMethod_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSomeDepInterface_SomeMethod_Call) Return(s string) *MockSomeDepInterface_SomeMethod_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockSomeDepInterface_SomeMethod_Call) RunAndReturn(run func() string) *MockSomeDepInterface_SomeMethod_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAnotherDepInterface creates a new instance of MockAnotherDepInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAnotherDepInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAnotherDepInterface {
	mock := &MockAnotherDepInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAnotherDepInterface is an autogenerated mock type for the AnotherDepInterface type
type MockAnotherDepInterface struct {
	mock.Mock
}

type MockAnotherDepInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAnotherDepInterface) EXPECT() *MockAnotherDepInterface_Expecter {
	return &MockAnotherDepInterface_Expecter{mock: &_m.Mock}
}

// AnotherMethod provides a mock function for the type MockAnotherDepInterface
func (_mock *MockAnotherDepInterface) AnotherMethod() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for AnotherMethod")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockAnotherDepInterface_AnotherMethod_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AnotherMethod'
type MockAnotherDepInterface_AnotherMethod_Call struct {
	*mock.Call
}

// AnotherMethod is a helper method to define mock.On call
func (_e *MockAnotherDepInterface_Expecter) AnotherMethod() *MockAnotherDepInterface_AnotherMethod_Call {
	return &MockAnotherDepInterface_AnotherMethod_Call{Call: _e.mock.On("AnotherMethod")}
}

func (_c *MockAnotherDepInterface_AnotherMethod_Call) Run(run func()) *MockAnotherDepInterface_AnotherMethod_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAnotherDepInterface_AnotherMethod_Call) Return(s string) *MockAnotherDepInterface_AnotherMethod_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockAnotherDepInterface_AnotherMethod_Call) RunAndReturn(run func() string) *MockAnotherDepInterface_AnotherMethod_Call {
	_c.Call.Return(run)
	return _c
}
