// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package subpackage

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockSomeSubDepInterface creates a new instance of MockSomeSubDepInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSomeSubDepInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSomeSubDepInterface {
	mock := &MockSomeSubDepInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSomeSubDepInterface is an autogenerated mock type for the SomeSubDepInterface type
type MockSomeSubDepInterface struct {
	mock.Mock
}

type MockSomeSubDepInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSomeSubDepInterface) EXPECT() *MockSomeSubDepInterface_Expecter {
	return &MockSomeSubDepInterface_Expecter{mock: &_m.Mock}
}

// SomeSubMethod provides a mock function for the type MockSomeSubDepInterface
func (_mock *MockSomeSubDepInterface) SomeSubMethod() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for SomeSubMethod")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockSomeSubDepInterface_SomeSubMethod_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SomeSubMethod'
type MockSomeSubDepInterface_SomeSubMethod_Call struct {
	*mock.Call
}

// SomeSubMethod is a helper method to define mock.On call
func (_e *MockSomeSubDepInterface_Expecter) SomeSubMethod() *MockSomeSubDepInterface_SomeSubMethod_Call {
	return &MockSomeSubDepInterface_SomeSubMethod_Call{Call: _e.mock.On("SomeSubMethod")}
}

func (_c *MockSomeSubDepInterface_SomeSubMethod_Call) Run(run func()) *MockSomeSubDepInterface_SomeSubMethod_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSomeSubDepInterface_SomeSubMethod_Call) Return(s string) *MockSomeSubDepInterface_SomeSubMethod_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockSomeSubDepInterface_SomeSubMethod_Call) RunAndReturn(run func() string) *MockSomeSubDepInterface_SomeSubMethod_Call {
	_c.Call.Return(run)
	return _c
}
